# Variables
title: Pedro Britto
description:
  Olá! Eu sou o Pedro, um desenvolvedor front end.
  Aqui compartilho tudo que aprendi em meus estudos.
baseurl: ""
url: "http://pedrobritto.com"

username_twitter: pibritto

# Includes
include: ["_pages"]

# Build settings
markdown: kramdown
exclude: [vendor]

sass:
  sass_dir: _sass

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/ # outputs every service.md file into its own folder under /servicos/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"

  - scope:
      path: ""
      type: "posts"
    values:
      author: "Pedro Britto"
      layout: "post"
      comments: true

  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "portfolio-item"
